server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mariadb://supercoding-1.cvksiw0qqv0f.ap-northeast-2.rds.amazonaws.com:3306/super_scheduler
    username: ${PROD_USERNAME}
    password: ${PROD_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://ec2-52-79-228-10.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/google

          kakao:
            redirect-uri: http://ec2-52-79-228-10.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/kakao

          naver:
            redirect-uri: http://ec2-52-79-228-10.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/naver

logging:
  config: classpath:logback-spring-prod.xml