server:
    port: 8080

socket:
    server:
        port: 9092
    alarm:
        port: 9093

spring:
    jwt:
        secret: ${SECRET_KEY}
        token:
            access-expiration-time: 43200000    # 12시간
            refresh-expiration-time: 604800000

    data:
        redis:
            host: localhost
            port: 6379
            timeout: 60000

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${GMAIL_USERNAME}
        password: ${GMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    config:
        import:
            - application-oauth2.yml

cloud:
    aws:
        s3:
            bucket: ${BUCKET_NAME}
        stack.auto: false
        region.static: ap-northeast-2
        credentials:
            accessKey: ${ACCESS_KEY}
            secretKey: ${S3_SECRET_KEY}